name: CI [frontend-app] prod

on:
  push:
    tags:
      - 'v*'

jobs:
  Test_and_build:
    name: NODE test, build and push code
    uses: Nexus-Ninjas/reusable-workflows/.github/workflows/node.yaml@main
    with:
      GH_ENVIRONMENT: PROD  
      ACTION: test  
    secrets: inherit
