name: CI [frontend-app] prod

on:
  push:
    tags:
      - 'v*'

jobs:
  Test:
    name: NODE test code    
    uses: Nexus-Ninjas/reusable-workflows/.github/workflows/node.yaml@main
    with:
      GH_ENVIRONMENT: PROD  
      ACTION: test  
    secrets: inherit
