name: CI [backend-app] SCAN

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
    branches:
      - 'main'
      - 'Develop'
      - 'QA'  
 
jobs:
  Scan:
    name: Snyk scan
    if: ${{ github.event.pull_request.merged == false }}
    uses: Nexus-Ninjas/reusable-workflows/.github/workflows/snyk.yaml@main
    with:
      CODEBASE : maven    
    secrets: inherit

  Code_quality:
    name: Sonar scan
    if: ${{ github.event.pull_request.merged == false }}
    uses: Nexus-Ninjas/reusable-workflows/.github/workflows/sonar.yaml@main  
    secrets: inherit
